gsl/urls.py
"""gsl URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/5.2/topics/http/urls/

"""

from django.contrib import admin
from django.urls import include, path

from gsl import settings

admin.site.site_header = "Back-office Turgot - " + settings.ENV
admin.site.index_title = "Back-office Turgot - " + settings.ENV
admin.site.site_title = "Back-office Turgot - " + settings.ENV

# Django's default handlers convert exception to string - we need these minimal
# handlers to pass the exception object so templates can duck type user_message
handler404 = "gsl_pages.views.custom_404_view"
handler403 = "gsl_pages.views.custom_403_view"
handler500 = "gsl_pages.views.custom_500_view"

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("gsl_oidc.urls")),
    path("", include("gsl_pages.urls")),
    path(
        "ds/",
        include(("gsl_demarches_simplifiees.urls", "gsl_demarches_simplifiees"), "ds"),
    ),
    path("oidc/", include("mozilla_django_oidc.urls")),
    path("projets/", include(("gsl_projet.urls", "gsl_projet"), "projet")),
    path(
        "simulation/",
        include(("gsl_simulation.urls", "gsl_simulation"), "simulation"),
    ),
    path(
        "programmation/",
        include(("gsl_programmation.urls", "gsl_programmation"), "programmation"),
    ),
    path(
        "notification/",
        include(("gsl_notification.urls", "gsl_notification"), "notification"),
    ),
]

if settings.DEBUG:
    from debug_toolbar.toolbar import debug_toolbar_urls
    from django.contrib.staticfiles.urls import staticfiles_urlpatterns

    urlpatterns += staticfiles_urlpatterns()
    urlpatterns += debug_toolbar_urls()

gsl_projet/urls.py
from django.urls import path

from gsl_programmation.views import (
    EnveloppeCreateView,
    EnveloppeDeleteView,
    EnveloppeUpdateView,
)

from . import views

urlpatterns = [
    path(
        "voir/<int:projet_id>/",
        views.get_projet,
        name="get-projet",
    ),
    path(
        "voir/<int:projet_id>/notes/",
        views.get_projet_notes,
        name="get-projet-notes",
    ),
    path("liste", views.ProjetListView.as_view(), name="list"),
    path(
        "enveloppe/ajouter/",
        EnveloppeCreateView.as_view(),
        name="enveloppe-create",
    ),
    path(
        "enveloppe/<int:pk>/modifier/",
        EnveloppeUpdateView.as_view(),
        name="enveloppe-update",
    ),
    path(
        "enveloppe/<int:pk>/supprimer/",
        EnveloppeDeleteView.as_view(),
        name="enveloppe-delete",
    ),
]

gsl_simulation/models.py
from django.db import models
from django.db.models import Count, QuerySet, Sum
from django.forms import ValidationError
from django_extensions.db.fields import AutoSlugField

from gsl_core.models import BaseModel, Collegue, Perimetre
from gsl_programmation.models import Enveloppe
from gsl_programmation.services.enveloppe_service import EnveloppeService
from gsl_projet.models import DotationProjet, Projet
from gsl_projet.utils.utils import compute_taux


class SimulationQuerySet(models.QuerySet):
    def containing_perimetre(self, perimetre: Perimetre):
        ancestors_qs = perimetre.ancestors()
        perimetres_to_filter = list(ancestors_qs) + [perimetre]
        return self.filter(enveloppe__perimetre__in=perimetres_to_filter)


class SimulationManager(models.Manager.from_queryset(SimulationQuerySet)):
    pass


class Simulation(BaseModel):
    title = models.CharField(verbose_name="Titre")
    created_by = models.ForeignKey(Collegue, on_delete=models.SET_NULL, null=True)
    enveloppe = models.ForeignKey(
        Enveloppe,
        on_delete=models.PROTECT,
        verbose_name="Enveloppe de dotation associée",
    )
    slug = AutoSlugField(
        verbose_name="Clé d’URL",
        unique=True,
        max_length=120,
        populate_from="title",
        blank=False,
    )

    objects = SimulationManager()

    class Meta:
        verbose_name = "Simulation"
        verbose_name_plural = "Simulations"

    def __str__(self):
        return self.title

    @property
    def dotation(self):
        return self.enveloppe.dotation

    def get_absolute_url(self):
        from django.urls import reverse

        if not self.slug:
            return reverse("simulation:simulation-form")

        return reverse("simulation:simulation-detail", kwargs={"slug": self.slug})

    def get_projet_status_summary(self):
        default_status_summary = {
            SimulationProjet.STATUS_PROCESSING: 0,
            SimulationProjet.STATUS_ACCEPTED: 0,
            SimulationProjet.STATUS_REFUSED: 0,
            SimulationProjet.STATUS_PROVISIONALLY_ACCEPTED: 0,
            SimulationProjet.STATUS_PROVISIONALLY_REFUSED: 0,
            "notified": 0,
        }
        status_count = (
            SimulationProjet.objects.filter(simulation=self)
            .values("status")
            .annotate(count=Count("status"))
        )

        summary = {item["status"]: item["count"] for item in status_count}

        return {**default_status_summary, **summary}

    def get_total_amount_granted(self, qs: QuerySet[Projet]):
        statuses_to_include = (
            SimulationProjet.STATUS_ACCEPTED,
            SimulationProjet.STATUS_PROVISIONALLY_ACCEPTED,
        )
        return (
            qs.filter(
                dotationprojet__simulationprojet__simulation=self,
                dotationprojet__simulationprojet__status__in=statuses_to_include,
            ).aggregate(Sum("dotationprojet__simulationprojet__montant"))[
                "dotationprojet__simulationprojet__montant__sum"
            ]
            or 0.0
        )


class SimulationProjetQuerySet(models.QuerySet):
    def in_user_perimeter(self, user: Collegue):
        if user.is_staff:
            return self.all()
        return self.filter(
            simulation__enveloppe__in=EnveloppeService.get_enveloppes_visible_for_a_user(
                user
            )
        )


class SimulationProjetManager(models.Manager.from_queryset(SimulationProjetQuerySet)):
    pass


class SimulationProjet(BaseModel):
    STATUS_PROCESSING = "draft"
    STATUS_ACCEPTED = "valid"
    STATUS_REFUSED = "cancelled"
    STATUS_PROVISIONALLY_ACCEPTED = "provisionally_accepted"
    STATUS_PROVISIONALLY_REFUSED = "provisionally_refused"
    STATUS_DISMISSED = "dismissed"

    STATUS_CHOICES = (
        (STATUS_PROCESSING, "🔄 En traitement"),
        (STATUS_ACCEPTED, "✅ Accepté"),
        (STATUS_PROVISIONALLY_ACCEPTED, "✔️ Accepté provisoirement"),
        (STATUS_PROVISIONALLY_REFUSED, "✖️ Refusé provisoirement"),
        (STATUS_REFUSED, "❌ Refusé"),
        (STATUS_DISMISSED, "⛔️ Classé sans suite"),
    )

    SIMULATION_PENDING_STATUSES = (
        STATUS_PROCESSING,
        STATUS_PROVISIONALLY_ACCEPTED,
        STATUS_PROVISIONALLY_REFUSED,
    )

    dotation_projet = models.ForeignKey(
        DotationProjet, on_delete=models.CASCADE, null=True
    )
    simulation = models.ForeignKey(
        Simulation, on_delete=models.CASCADE, null=True, blank=True
    )

    montant = models.DecimalField(
        decimal_places=2, max_digits=14, verbose_name="Montant"
    )
    status = models.CharField(
        verbose_name="État", choices=STATUS_CHOICES, default=STATUS_PROCESSING
    )

    objects = SimulationProjetManager()

    class Meta:
        verbose_name = "Projet de simulation"
        verbose_name_plural = "Projets de simulation"
        constraints = (
            models.UniqueConstraint(
                fields=("dotation_projet", "simulation"),
                name="unique_projet_simulation",
                nulls_distinct=True,
            ),
        )

    def __str__(self):
        return f"Simulation projet {self.pk}"

    def save(self, *args, **kwargs):
        self.clean()
        super().save(*args, **kwargs)

    def get_absolute_url(self):
        from django.urls import reverse

        return reverse("simulation:simulation-projet-detail", kwargs={"pk": self.pk})

    @property
    def projet(self):
        return self.dotation_projet.projet

    @property
    def dossier(self):
        return self.projet.dossier_ds

    @property
    def enveloppe(self):
        return self.simulation.enveloppe

    @property
    def dotation(self):
        return self.dotation_projet.dotation

    @property
    def taux(self):
        return compute_taux(self.montant, self.dotation_projet.assiette_or_cout_total)

    def clean(self):
        errors = {}
        self._validate_montant(errors)
        self._validate_dotation(errors)
        if errors:
            raise ValidationError(errors)

    def _validate_montant(self, errors):
        if self.dotation_projet.assiette is not None:
            if self.montant and self.montant > self.dotation_projet.assiette:
                errors["montant"] = (
                    "Le montant de la simulation ne peut pas être supérieur à l'assiette du projet."
                )
        else:
            if (
                self.montant
                and self.projet.dossier_ds.finance_cout_total
                and self.montant > self.projet.dossier_ds.finance_cout_total
            ):
                errors["montant"] = (
                    "Le montant de la simulation ne peut pas être supérieur au coût total du projet."
                )

    def _validate_dotation(self, errors):
        if self.dotation_projet.dotation != self.simulation.enveloppe.dotation:
            errors["dotation_projet"] = {
                "La dotation du projet doit être la même que la dotation de la simulation."
            }

gsl_projet/views.py
from functools import cached_property

from django.db.models import Sum
from django.shortcuts import get_object_or_404, redirect, render
from django.urls import reverse
from django.views.decorators.http import require_GET
from django.views.generic import ListView
from django_filters.views import FilterView

from gsl_core.exceptions import Http404
from gsl_projet.constants import PROJET_STATUS_CHOICES
from gsl_projet.services.projet_services import ProjetService
from gsl_projet.utils.django_filters_custom_widget import CustomSelectWidget
from gsl_projet.utils.filter_utils import FilterUtils
from gsl_projet.utils.projet_filters import BaseProjetFilters, ProjetOrderingFilter
from gsl_projet.utils.projet_page import PROJET_MENU

from .models import CategorieDetr, Projet


def projet_visible_by_user(func):
    def wrapper(*args, **kwargs):
        user = args[0].user
        if user.is_staff:
            return func(*args, **kwargs)

        projet = get_object_or_404(Projet, id=kwargs["projet_id"])
        is_projet_visible_by_user = (
            Projet.objects.for_user(user).filter(id=projet.id).exists()
        )
        if not is_projet_visible_by_user:
            raise Http404(user_message="Projet non trouvé")

        return func(*args, **kwargs)

    return wrapper


def _get_projet_context_info(projet_id):
    projet = get_object_or_404(Projet, id=projet_id)
    title = projet.dossier_ds.projet_intitule
    context = {
        "title": title,
        "projet": projet,
        "dossier": projet.dossier_ds,
        "breadcrumb_dict": {
            "current": title,
        },
        "menu_dict": PROJET_MENU,
        "projet_notes": projet.notes.all(),
        "dotation_projets": projet.dotationprojet_set.all(),
    }
    return context


@projet_visible_by_user
@require_GET
def get_projet(request, projet_id):
    context = _get_projet_context_info(projet_id)
    return render(request, "gsl_projet/projet.html", context)


@projet_visible_by_user
@require_GET
def get_projet_notes(request, projet_id):
    context = _get_projet_context_info(projet_id)
    return render(request, "gsl_projet/projet/tab_notes.html", context)


class ProjetListViewFilters(BaseProjetFilters):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        if hasattr(self.request, "user") and self.request.user.perimetre:
            perimetre = self.request.user.perimetre
            self.filters["territoire"].extra["choices"] = tuple(
                (p.id, p.entity_name) for p in (perimetre, *perimetre.children())
            )
            if perimetre.departement:
                self.filters["categorie_detr"].extra["choices"] = tuple(
                    (c.id, c.libelle)
                    for c in CategorieDetr.objects.current_for_departement(
                        perimetre.departement
                    )
                )

    ORDERING_MAP = {
        **BaseProjetFilters.ORDERING_MAP,
        "montant_retenu_total": "montant_retenu",
    }

    ORDERING_LABELS = {
        **BaseProjetFilters.ORDERING_LABELS,
        "montant_retenu_total": "Montant retenu",
    }

    order = ProjetOrderingFilter(
        fields=ORDERING_MAP,
        field_labels=ORDERING_LABELS,
        empty_label="Tri",
        widget=CustomSelectWidget,
    )

    filterset = (
        "territoire",
        "porteur",
        "dotation",
        "status",
        "cout_total",
        "montant_demande",
        "montant_retenu",
        "categorie_detr",
    )

    @property
    def qs(self):
        qs = super().qs
        qs = qs.annotate(
            montant_retenu_total=Sum("dotationprojet__programmation_projet__montant")
        )
        qs = qs.for_user(self.request.user)
        qs = qs.for_current_year()
        qs = qs.select_related(
            "address",
            "address__commune",
            "demandeur",
            "dossier_ds",
            "dossier_ds__perimetre",
            "dossier_ds__demande_categorie_detr",
            "dossier_ds__demande_categorie_dsil",
        ).prefetch_related(
            # "dotationprojet_set__detr_categories", # TODO category : useless now. Remove it if we don't allow to set DETR category. The code is commented to enhance performance.
            "dotationprojet_set__programmation_projet",
        )
        return qs


class ProjetListView(FilterView, ListView, FilterUtils):
    model = Projet
    paginate_by = 25
    filterset_class = ProjetListViewFilters
    template_name = "gsl_projet/projet_list.html"
    STATE_MAPPINGS = {key: value for key, value in PROJET_STATUS_CHOICES}

    def get(self, request, *args, **kwargs):
        if "reset_filters" in request.GET:
            if request.path == reverse("gsl_projet:list"):
                return redirect(request.path)
            else:
                return redirect("/")
        return super().get(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        qs_global = (
            self.filterset.qs
        )  # utile pour ne pas avoir la pagination de context["object_list"]
        context["title"] = "Projets"
        context["breadcrumb_dict"] = {}
        context["total_cost"] = ProjetService.get_total_cost(qs_global)
        context["total_amount_asked"] = ProjetService.get_total_amount_asked(qs_global)
        context["total_amount_granted"] = ProjetService.get_total_amount_granted(
            qs_global
        )
        context["enveloppes"] = (
            self.request.user.perimetre.enveloppe_set.for_current_year().all()
        )
        context["enveloppes_with_children"] = True
        self.enrich_context_with_filter_utils(context, self.STATE_MAPPINGS)

        return context

    def _get_perimetre(self):
        if hasattr(self.request, "user") and self.request.user.perimetre:
            return self.request.user.perimetre

    def _get_territoire_choices(self):
        perimetre = self._get_perimetre()
        if not perimetre:
            return ()

        return (perimetre, *perimetre.children())

    # TODO category : useless now. Remove it unless we use it to filter DETR projects.
    @cached_property
    def categorie_detr_choices(self):
        perimetre = self._get_perimetre()
        if not perimetre:
            return ()

        if not perimetre.departement:
            return ()

        return CategorieDetr.objects.current_for_departement(perimetre.departement)

gsl_projet/templates/includes/_annotations_detail.html
<h2>
    <span class="fr-icon-edit-box-fill fr-icon--lg blue-color"
          aria-hidden="true"></span>
    Notes pour l’instruction du projet
</h2>
{% if projet.dossier_ds.has_annotations_champ_libre %}
    {% if projet.dossier_ds.annotations_champ_libre_1 %}
        <h3>
            Champ libre pour le service instructeur 1 (Démarche Numérique)
        </h3>
        <div class="fr-background-alt--blue-france fr-mb-4w fr-p-2w note-champ-libre">
            {{ projet.dossier_ds.annotations_champ_libre_1|linebreaks }}
        </div>
    {% endif %}
    {% if projet.dossier_ds.annotations_champ_libre_2 %}
        <h3>
            Champ libre pour le service instructeur 2 (Démarche Numérique)
        </h3>
        <div class="fr-background-alt--blue-france fr-mb-4w fr-p-2w note-champ-libre">
            {{ projet.dossier_ds.annotations_champ_libre_2|linebreaks }}
        </div>
    {% endif %}
    {% if projet.dossier_ds.annotations_champ_libre_3 %}
        <h3>
            Champ libre pour le service instructeur 3 (Démarche Numérique)
        </h3>
        <div class="fr-background-alt--blue-france fr-mb-4w fr-p-2w note-champ-libre">
            {{ projet.dossier_ds.annotations_champ_libre_3|linebreaks }}
        </div>
    {% endif %}
{% else %}
    <h3>
        Champ libre pour le service instructeur (Démarche Numérique)
    </h3>
    <p>
        <i>Aucun champ libre n’a été renseigné.</i>
    </p>
{% endif %}

{% block block_projet_notes %}
{% endblock block_projet_notes %}

gsl_projet/templates/includes/_filter_categorie_detr.html
{% if categorie_detr_choices|length > 1 %}
    <div class="filter-field fr-col-12 fr-col-md-4 fr-col-lg-2">
        <div class="gsl-dropdown">
            <label class="fr-label" id="filter_categorie_detr_label">
                <span class="fr-sr-only">Filtrer par</span>
                Catégorie DETR
            </label>
            <button type="button"
                    class="fr-select {% if is_categorie_detr_active %}filter-dropdown-button-active{% endif %}">
                {{ categorie_detr_placeholder }}
            </button>
            <div id="filter-categorie_detr"
                 class="gsl-dropdown-content"
                 role="group"
                 aria-describedby="filter_categorie_detr_label">
                <div>
                    {% for categorie in categorie_detr_choices %}
                        <div class="fr-checkbox-group fr-checkbox-group--sm">
                            <input type="checkbox"
                                   name="categorie_detr"
                                   value="{{ categorie.id }}"
                                   id="id_categorie_detr_{{ forloop.counter }}"
                                   {% if categorie.id in categorie_detr_selected %}checked{% endif %}>
                            <label for="id_categorie_detr_{{ forloop.counter }}" class="fr-label">
                                {{ categorie.label }}
                            </label>
                        </div>
                    {% endfor %}
                </div>
                <button type="submit" class="fr-btn fr-btn--sm stick-to-bottom fr-mt-2w">
                    Filtrer
                </button>
            </div>
        </div>
    </div>
{% endif %}

gsl_projet/templates/includes/_filter_cout_total.html
<div class="filter-field fr-col-12 fr-col-md-4 fr-col-lg-2">
    <div class="gsl-dropdown fr-mt-4w">
        <button type="button"
                class="fr-input {% if is_cout_total_active %}filter-dropdown-button-active{% endif %}"
                id="filter-total-cost-button">
            <span class="fr-icon-coin-fill fr-icon--sm blue-color fr-mr-1w"></span>
            Coût total
        </button>
        <div class="gsl-dropdown-content">
            <div class="amount-filter-group">
                <label class="fr-label" for="id_cost_min">
                    Coût minimum
                </label>
                <div class="euro-input-wrap">
                    {{ filter.form.cout_min }}
                    <span class="euro-input-symbol">€</span>
                </div>
            </div>
            <div class="amount-filter-group">
                <label class="fr-label" for="id_cost_max">
                    Coût maximum
                </label>
                <div class="euro-input-wrap">
                    {{ filter.form.cout_max }}
                    <span class="euro-input-symbol">€</span>
                </div>
            </div>
            <button type="submit" class="fr-btn fr-btn--sm">
                Filtrer
            </button>
        </div>
    </div>
</div>

gsl_projet/templates/includes/_filter_dotation.html
{% load ui_tags %}

{% ui_multiselect id="id_dotation" field=filter.form.dotation label="Dotation" placeholder=dotation_placeholder is_active=is_dotation_active %}

gsl_projet/templates/includes/_filter_status.html
{% load ui_tags %}

{% ui_multiselect id="id_status" field=filter.form.status label="Statut" placeholder=status_placeholder is_active=is_status_active size="S" %}

gsl_projet/templates/includes/_projets_table.html
{% load gsl_filters dsfr_tags custom_pluralize %}

<div class="fr-table fr-table--multiline fr-table--xs fr-table--no-caption gsl-projet-table"
     id="projet-table">
    <div class="fr-table__wrapper">
        <div class="fr-table__container">

            <div class="fr-table__content">
                <table id="table-projets">
                    <caption>Liste des projets</caption>
                    <thead>
                        <tr>
                            <th scope="col">
                                Date de dépôt
                            </th>
                            <th scope="col">
                                Intitulé du projet
                            </th>
                            <th scope="col">
                                Demandeur
                            </th>
                            <th scope="col">
                                N° D.N.
                            </th>
                            <th scope="col">
                                Dotation
                            </th>
                            <th scope="col">
                                Coût total du projet (€)
                                <br>
                                <span class="gsl-money gsl-projet-table__total gsl-projet-table__total--cost">{{ total_cost | euro:0 }}</span>
                            </th>
                            <th scope="col">
                                Montant et taux sollicités (€)
                                <br>
                                <span class="gsl-money gsl-projet-table__total gsl-projet-table__total--asked">{{ total_amount_asked | euro:0 }}</span>
                            </th>
                            <th scope="col">
                                Montant retenu (€)
                                <br>
                                <span class="gsl-money gsl-projet-table__total gsl-projet-table__total--granted">{{ total_amount_granted | euro:0 }}</span>
                            </th>
                            <th scope="col">
                                Taux de subvention (%)
                            </th>
                            <th scope="col">
                                Catégorie d'opération
                            </th>
                            <th scope="col" class="gsl-projet-table__col--w120">
                                Statut
                            </th>
                            <th scope="col">
                                <span class="fr-sr-only">Actions</span>
                            </th>
                        </tr>
                    </thead>
                    <tbody id="projet-list">
                        {% for projet in object_list %}
                            {% with projet.dotationprojet_set.all|sort:"dotation" as dotation_projets %}
                                <tr>
                                    <td class="fr-cell--center">
                                        {{ projet.dossier_ds.ds_date_depot|date:"d/m/Y" }}
                                        {% if projet.dossier_ds.demande_numero_demande_precedente %}
                                            <br />
                                            <span class="fr-tag fr-tag--sm fr-tag--icon-left fr-icon-arrow-turn-back-line fr-mt-0-5v">
                                                Reporté
                                            </span>
                                        {% endif %}
                                    </td>
                                    <td>
                                        <span class="max-3-lines" title="{{ projet.dossier_ds.projet_intitule }}">
                                            {{ projet.dossier_ds.projet_intitule }}
                                        </span>
                                    </td>
                                    <td>
                                        <span class="max-3-lines"
                                              title="{{ projet.demandeur.name | format_demandeur_nom }}">
                                            {{ projet.demandeur.name | format_demandeur_nom }}
                                        </span>
                                    </td>
                                    <td>
                                        {{ projet.dossier_ds.ds_number }}
                                    </td>
                                    {% if projet.dossier_ds.is_sans_pieces and not projet.dossier_ds.demande_dispositif_sollicite %}
                                        <td class="gsl-money" colspan="3">
                                            <a href="{% url 'gsl_demarches_simplifiees:dossier-sans-piece-update' projet.dossier_ds.pk %}"
                                               class="fr-link fr-link--xs fr-link--icon-right fr-icon-edit-line">Renseigner
                                                les
                                            informations</a>
                                        </td>
                                    {% else %}
                                        <td class="gsl-projet-table__cell--dotation">
                                            {% for dp in dotation_projets %}
                                                <span>{{ dp.dotation }}</span>
                                            {% endfor %}
                                        </td>
                                        <td class="gsl-money">
                                            {{ projet.dossier_ds.finance_cout_total|euro_value }}
                                        </td>
                                        <td class="gsl-money">
                                            {{ projet.dossier_ds.demande_montant|euro_value }}
                                        </td>
                                    {% endif %}
                                    <td class="gsl-money {% if projet.montant_retenu is not None %} gsl-projet-table__montant-retenu {% endif %} gsl-projet-table__cell--dotation">
                                        {% for dp in dotation_projets %}
                                            <span>{{ dp.montant_retenu|euro_value }}</span>
                                        {% endfor %}
                                    </td>
                                    <td class="gsl-money gsl-projet-table__cell--dotation">
                                        {% for dp in dotation_projets %}
                                            <span>{{ dp.taux_retenu|percent_value }}</span>
                                        {% endfor %}
                                    </td>
                                    <td>
                                        {% for dp in dotation_projets %}
                                            <div>
                                                {% if dp.dotation == "DSIL" %}
                                                    <span class="max-3-lines"
                                                          title="{{ projet.dossier_ds.demande_categorie_dsil.label }}">
                                                        {{ projet.dossier_ds.demande_categorie_dsil.label }}
                                                    </span>
                                                {% elif dp.dotation == "DETR" %}
                                                    {% if projet.dossier_ds.demande_has_categorie_detr == False %}
                                                        Hors catégorie
                                                    {% else %}
                                                        <span class="max-3-lines"
                                                              title="{{ projet.dossier_ds.demande_categorie_detr.complete_label }}">
                                                            {{ projet.dossier_ds.demande_categorie_detr.complete_label }}
                                                        </span>
                                                    {% endif %}
                                                {% endif %}
                                            </div>
                                        {% endfor %}
                                    </td>
                                    <td class="gsl-projet-table__cell--dotation">
                                        {% for dp in dotation_projets %}
                                            <div>
                                                <span class="projet_status__{{ dp.status }}">{{ dp.get_status_display }}</span>
                                                {% if projet.to_notify %}
                                                    <span class="projet-notification-status projet__to_notify">À notifier</span>
                                                {% elif projet.notified_at %}
                                                    <span class="projet-notification-status projet__notified">Notifié</span>
                                                {% endif %}
                                            </div>
                                        {% endfor %}
                                    </td>
                                    <td class="fr-cell--right">
                                        <a class="fr-btn--tertiary-no-outline gsl-no-underline"
                                           href="{{ projet.get_absolute_url }}{% querystring %}">
                                            <span class="fr-sr-only">Voir le projet {{ projet.dossier_ds.ds_number }}</span>
                                            <span class="fr-icon-arrow-right-s-line" aria-hidden="true"></span>
                                        </a>
                                    </td>
                                </tr>
                            {% endwith %}
                        {% empty %}
                            <tr>
                                <td colspan="12">
                                    Liste vide.
                                </td>
                            </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>
    <div class="fr-table__footer">
        <div class="fr-table__footer--middle">
            {% dsfr_pagination page_obj %}
        </div>
    </div>
</div>